### PR TITLE
Remove username from connection string for Redis 6

### LINKED ISSUE #30: Username "h" in connection string results in WRONGPASS errors for Redis 6+
In the past, Heroku was adding the `h` username on Redis connection strings (see: https://devcenter.heroku.com/changelog-items/1932). With the release of Redis 6 and ACLs (https://redis.io/docs/manual/security/acl/), Heroku stopped adding the `h` username for Redis 6 instances (and new Redis add-ons using older Redis versions).

However, this buildpack is still hardcoding the `h` username:  https://github.com/heroku/heroku-buildpack-ci-redis/blob/master/bin/compile#L68 in the connection string config var.

This is resulting in `WRONGPASS invalid username-password pair or user is disabled.` errors with Redis 6+ if the Redis clients are trying to authenticate using the `h` username and the given password.

With Redis 6+, using `requirepass` will configure that pass for the `default` user. The `h` user wouldn't exist, neither it's configured with that password, so connections using `username=h, password=xxxx` would fail. (Although one could use `username=default, password=xxx` and that'd work). We run `requirepass` here: https://github.com/heroku/heroku-buildpack-ci-redis/blob/master/bin/compile#L71.

We've seen reports of this issue after 6.2 was made the default version as part of https://github.com/heroku/heroku-buildpack-ci-redis/pull/29. I'm admittedly confused as of why we didn't get reports of the same problem before, when 6.0.9 was the default version, which should have worked similarly in terms of users/ACLs.

As a result, this is resulting in test failures in Heroku CI when the Redis client tries to connect to the locally running instance and authenticate as the `h` user. We've seen this happen with `redis-py` (3.5.3, and also tested with 4.3.1 through a console directly - outside of Heroku CI).

Some other clients like `redis-rb` are handling this scenario specifically but raising a warning:

```
[redis-rb] The Redis connection was configured with username "h", but the provided password was for the default user. This will start failing in redis-rb 5.0.0.
```
(https://github.com/redis/redis-rb/blob/4724c1bfde2d5679128ced8ec7b46bac66605b7b/lib/redis/client.rb#L124-L134)

To sort this out, the `REDIS_URL` config var shouldn't include the `h` username at least if the version is 6 or higher.

### PR DESCRIPTION
**Pull request by iriberri**
Fixes https://github.com/heroku/heroku-buildpack-ci-redis/issues/30

### CODE REVIEW

File: bin/compile [hunk 1]
```diff
@@ -65,7 +65,14 @@ fi
 
 set-env PATH '/app/.indyno/vendor/redis/bin:$PATH'
 PASSWORD=`openssl rand -hex 16`
-export REDIS_URL="redis://h:$PASSWORD@localhost:6379/"
+
+# placeholder username h was added for compatibility with old Redis clients (https://devcenter.heroku.com/changelog-items/1932) and is incompatible with Redis 6 AUTH
+if [[ "${VERSION}" == 6* ]]; then
```
Comment (edmorley) [inline bin/compile]: I'm sure Redis 60 won't be out for a bit, but for completeness we may want to add the trailing dot :-)
(This should work, since at the time of the check, `VERSION` has been expanded to the full version string, even if the customer specified `"6"`)

```suggestion
if [[ "${VERSION}" == 6.* ]]; then
```

File: bin/test.sh [hunk 2]
```diff
@@ -20,7 +20,7 @@ echo "Checking redis-server presence and version..."
 
 # Redis <4 does not support connection URLs so REDIS_URL has to be parsed:
```
Comment (iriberri) [inline bin/test.sh:21]: We might want to use the `-u` option in `redis-cli` now instead of parsing this, though.

**Review by edmorley — APPROVED** [review]
This is great - thank you for fixing!

I also spotted #23, if you wanted to drop the trailing slash at same time as doing this? (To make the tests pass it will also need a slight tweak to the test.sh regex too.)
However completely up to you, that one isn't urgent.

Longer term, I wonder when we can drop support for Redis 3 from this buildpack so the test.sh URL parsing isn't required (since newer Redis can just use the Redis URL directly).

File: bin/test.sh (hunk 2 above)
Comment (iriberri) [reply bin/test.sh:21]: Update: To use `redis-cli -u` we'd need to remove the `:` before the password to make Redis understand it shouldn't use a username, so it wouldn't work directly.

File: bin/compile (hunk 1 above)
Comment (iriberri) [reply bin/compile]: Haha, thank you - that's completely true. I was thinking about that use case explicitly and as you say we'd expand it already.

**Comment by iriberri** [comment]
@edmorley thanks! I remember #23 but I don't have all the context for this right now. Although it sounds like a safe change I don't know if this could potentially break something (including existing customer workarounds to remove it). I can take care of investigating that deeper, but I prefer to handle it in a separate PR to not delay this fix.

**Comment by edmorley** [comment]
Published:

```
$ h buildpacks:publish heroku/ci-redis master
Publishing buildpack heroku/ci-redis... done
Publishing buildpack was successful

$ h buildpacks:versions heroku/ci-redis | head -n4
Version  Released At               Status
───────  ────────────────────────  ─────────
10       2022-06-01T16:03:34.612Z  published
9        2022-05-19T08:31:51.168Z  published
```
